#!/usr/bin/env bash                                                             
# Displays "Best School" 10 times using a while loop.                           

counter=0

until [ $counter -eq 10 ]
do
        echo "Best School"
        (( counter++ ))
done
