#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop
# Displays "Hi" before "Best School" on the 9 iteration


counter=1

while [ $counter -le 10 ]
do
	echo "Best School"
	if [ $counter -eq 9 ]
	then
		echo "Hi"
	fi
        (( counter++ ))
done
